language: ruby
rvm:
- 2.4.1
services:
- mysql
bundler_args: "--without development --deployment -j4"
cache: bundler
before_script:
- mysql -e 'create database travis_ci_test;'
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:setup
script:
- bundle exec rake test
notifications:
  email: false
  slack:
    secure: my+EvCmEVVDTzJGJjb7SuNHEXj5mWOBSCXLupOUOjK3MW6TOlSaWw0I8vUAe54Vwt9KmxuHADF/mv5Hvn5oG0y4ua3OiOkX/Q4/Wrxsds+lgZ2V5qZ/iZvwIP94kr4qfbIFlGeZa+qngviTOqT3ou0cHh0PzTdU0fArCd3qwrhRxmJnf5zdT/dR7YZTo+Q+b3gch+uYGe1Wgc59oFRnGTM1PHowhVCshc50Od5sSHoIOOWPQcg8MeVKNTPJ8UMreVxRmatEYj+zwu60/JOuVIFTH2qv0EQLUQWN2zKyr9zp2TVKeW1YTjHtbimN9sgBASnaJQ9aCqTO+UT6y4cCxM2B2iE8tGCsJSkuD7gf/qo3XYhE0/JsS4Py9TyxxPf2XdyXUvWe4SqDMmZf03MPz6r3feSITgPwbJBQgGUEq/u9guXlY6TEp6wTRD5XJs769pd+ULgzlzDN7AwmZ3v/LiriWd77x5mwlAOnhefEC0Lsd/FPGrn7qdB6m5PIgZk//G6PpV6o/df/uvXwzu5UKdJ2TgFcgKNAd0dUks0gRprj/l36WhhTEVaMWnLX4pwpbP5BDCuKHfmRZXY5fzldM0JqfGpqoCkFpQiCkoz6Y7ErYwZ16JSNdW+L6nAmIHsWHYEBIpf3rriy5Fzadq43nAzCVw6RAVcTXEHkDveaYvQg=
