default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: skyline_development

test:
  <<: *default
  database: skyline_test

production:
  <<: *default
  database: skyline_production
